#!/usr/bin/env bash

#SBATCH --job-name=diamond_co_uhgp
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=48G

set -euo pipefail

# The purpose of this workflow is to look for matches to the UHGP in the best-hit proteins from the co-assemblies
# Since all sample information has been encoded in the FASTA headers, we can later extract the contig_id, subject_id, and closest_query 

# Define variables
#===========================================================================
project_dir="$SCRATCH/PRJEB76307_MGX"
scripts_dir="$SCRATCH/castalagin_stool_metagenomics/PRJEB76307_metagenomics" # Scripts from repository
diamond_dir="${project_dir}/diamond_co_out" # Contains the query FASTA file generated by the previous script

# Create output directory for diamond_uhgp output
diamond_uhgp_dir="${project_dir}/diamond_co_uhgp_out"
mkdir -p "${diamond_uhgp_dir}"

# Set the diamond tool thresholds
min_seq_id=60 # Could filter more stringently afterwards
min_coverage=60 # Must cover most of the subject (predicted proteins)
k_value=0   # Unlimited hits per query per sample

# Set the query FASTA file (best hits from the previous diamond search)
query="${diamond_dir}/diamond_co_best_hits.fasta"
uhgp_dir="$SCRATCH/uhgp" # See castalagin_stool_metagenomics/database_downloads/02_uhgp_download.sh
hits_tsv="${diamond_uhgp_dir}/all_hits_uhgp-100.tsv"
metadata="${uhgp_dir}/uhgp_genomes_all_metadata.tsv"
#===========================================================================

# Load modules
module load diamond/2.1.11 StdEnv/2023

diamond blastp \
  -q "$query" \
  -d "${uhgp_dir}/uhgp-100" \
  -o "${hits_tsv}" \
  --outfmt 6 qseqid sseqid pident ppos length qlen slen qstart qend sstart send evalue bitscore full_qseq full_sseq \
  --id ${min_seq_id} \
  --subject-cover ${min_coverage} \
  -k ${k_value} \
  --threads ${SLURM_CPUS_PER_TASK}

echo "Finished search against the UHGP"

# Annotate the hits table by adding metadata, extracting UHGP genome references, contig_id, subject_id, and closest_query
export diamond_uhgp_dir
export hits_tsv
export metadata

# Load modules
module load StdEnv/2023 python/3.13.2 scipy-stack/2026a

python3 "${scripts_dir}/diamond_co_uhgp_annotate.py"

echo "Finished merging the diamond UHGP table with UHGP metadata"

# Match patterns (in the best-hits table) from query FASTA headers to extract operon and gene names based on the pattern_mapping.tsv file
python3 "${scripts_dir}/string_pattern_mapping.py" "${diamond_uhgp_dir}/best_hits_uhgp-100_metadata.tsv" "${scripts_dir}/pattern_mapping.tsv" "${diamond_uhgp_dir}/best_hits_uhgp-100_metadata_operon.tsv"

echo "Finished annotating the UHGP best hits table with gene and operon information"
